[kafka]
kafka-1 ansible_host=10.10.10.11 kafka_node_id=1
kafka-2 ansible_host=10.10.10.12 kafka_node_id=2
kafka-3 ansible_host=10.10.10.13 kafka_node_id=3

[kafka:vars]
ansible_user=ubuntu
ansible_become=true
